name: Clojure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        cd clj-brcode 
        curl -s https://api.github.com/repos/naomijub/brcode/releases/latest \
        | grep "browser_download_url.*dylib" \
        | cut -d : -f 2,3 \
        | tr -d \" \
        | wget -qi -
        lein test
