name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd dartbrcode/
        pub get
    - name: Run tests
      run: |
        cd dartbrcode/
        curl -s https://api.github.com/repos/naomijub/brcode/releases/latest \
        | grep "browser_download_url.*so" \
        | cut -d : -f 2,3 \
        | tr -d \" \
        | wget -qi -
        pub run test test/lib.dart 
